version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shopperproject-api
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '80:3000'
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/shopperproject-api?schema=public
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db
    volumes:
      - ./public/uploads:/app/public/uploads 

volumes:
  pgdata:
