version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shopperproject-api
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '80:3000'
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/shopperproject-api?schema=public
    depends_on:
      - db
